module_name: Fixer.io Module
compatible_versions: 1.0.0+
author: thirty bees
category: administration
tags:
  - payment
  - currency
  - exchange rates
description_short: Provides currency exchange rates from fixer.io. Source: European Central Bank.
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL 3.0
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
